spring:
  application.name: RecipeFinder
  ai:
    # Define AI provider(s) for type of models for autoconfiguration
    model:
      chat: ollama
      embedding: ollama
    # AI provider configuration
    ollama:
      chat:
        model: llama3.2
        options.temperature: 0.5
      embedding.model: llama3.2

    # Logging
    chat.client.observations:
      log-prompt: true
      log-completion: true
      include-error-logging: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
