spring:
  application.name: RecipeFinder
  ai:
    # Define AI provider(s) for type of models for autoconfiguration
    model:
      chat: ollama
      embedding: ollama
      image: none
      audio:
        speech: none
        transcription: none
      moderation: none
    # AI provider configuration
    ollama:
      chat:
        model: qwen3
        options.temperature: 0.5
